/**
 * FAMÍLIAS DE ABERTURA — inglês → português.
 *
 * O TSV do Lichess traz `"Sicilian Defense: Najdorf Variation"`. Traduzir as
 * 3.810 linhas à mão não acontece; mas o texto ANTES do `:` tem só 149 valores
 * distintos, e é o único pedaço que a tela mostra. A variante fica no dado, em
 * inglês, fora da tela — traduzi-la está registrado como fora de escopo.
 *
 * ESTA TABELA NÃO PODE APODRECER: `npm run aberturas:gerar` **falha** se
 * aparecer família sem tradução, e `npm run verify:aberturas` falha também no
 * sentido contrário, se sobrar tradução órfã. Upstream mudou um nome, alguém
 * tem de olhar.
 *
 * Sobre as famílias com vírgula (`"London System, with Bd3"`): o sufixo faz
 * parte do nome da família no TSV, então entra aqui inteiro. As letras de peça
 * que aparecem nesses sufixos são todas `B` — Bishop em inglês, Bispo em
 * português —, então o lance se lê igual nas duas línguas e fica como está.
 */
export const FAMILIAS_PT: Record<string, string> = {
  "Alekhine Defense": "Defesa Alekhine",
  "Amar Opening": "Abertura Amar",
  "Amazon Attack": "Ataque Amazona",
  "Amsterdam Attack": "Ataque Amsterdã",
  "Anderssen's Opening": "Abertura Anderssen",
  "Australian Defense": "Defesa Australiana",
  "Barnes Defense": "Defesa Barnes",
  "Barnes Opening": "Abertura Barnes",
  "Basque Opening": "Abertura Basca",
  "Benko Gambit": "Gambito Benko",
  "Benko Gambit Accepted": "Gambito Benko Aceito",
  "Benko Gambit Declined": "Gambito Benko Recusado",
  "Benoni Defense": "Defesa Benoni",
  "Bird Opening": "Abertura Bird",
  "Bishop's Opening": "Abertura do Bispo",
  "Blackmar-Diemer Gambit": "Gambito Blackmar-Diemer",
  "Blackmar-Diemer Gambit Accepted": "Gambito Blackmar-Diemer Aceito",
  "Blackmar-Diemer Gambit Declined": "Gambito Blackmar-Diemer Recusado",
  "Blumenfeld Countergambit": "Contragambito Blumenfeld",
  "Blumenfeld Countergambit Accepted": "Contragambito Blumenfeld Aceito",
  "Bogo-Indian Defense": "Defesa Bogo-Índia",
  "Bongcloud Attack": "Ataque Bongcloud",
  "Borg Defense": "Defesa Borg",
  "Canard Opening": "Abertura Canard",
  "Caro-Kann Defense": "Defesa Caro-Kann",
  "Carr Defense": "Defesa Carr",
  "Catalan Opening": "Abertura Catalã",
  "Center Game": "Jogo do Centro",
  "Center Game Accepted": "Jogo do Centro Aceito",
  "Clemenz Opening": "Abertura Clemenz",
  "Colle System": "Sistema Colle",
  "Creepy Crawly Formation": "Formação Creepy Crawly",
  "Czech Defense": "Defesa Tcheca",
  "Danish Gambit": "Gambito Dinamarquês",
  "Danish Gambit Accepted": "Gambito Dinamarquês Aceito",
  "Danish Gambit Declined": "Gambito Dinamarquês Recusado",
  "Dresden Opening": "Abertura Dresden",
  "Duras Gambit": "Gambito Duras",
  "Dutch Defense": "Defesa Holandesa",
  "Döry Defense": "Defesa Döry",
  "East Indian Defense": "Defesa Índia do Leste",
  "Elephant Gambit": "Gambito do Elefante",
  "English Defense": "Defesa Inglesa",
  "English Opening": "Abertura Inglesa",
  "English Orangutan": "Orangotango Inglês",
  "Englund Gambit": "Gambito Englund",
  "Englund Gambit Declined": "Gambito Englund Recusado",
  "Formation": "Formação",
  "Four Knights Game": "Jogo dos Quatro Cavalos",
  "French Defense": "Defesa Francesa",
  "Fried Fox Defense": "Defesa Fried Fox",
  "Global Opening": "Abertura Global",
  "Goldsmith Defense": "Defesa Goldsmith",
  "Grob Opening": "Abertura Grob",
  "Grünfeld Defense": "Defesa Grünfeld",
  "Gunderam Defense": "Defesa Gunderam",
  "Hippopotamus Defense": "Defesa Hipopótamo",
  "Horwitz Defense": "Defesa Horwitz",
  "Hungarian Opening": "Abertura Húngara",
  "Indian Defense": "Defesa Índia",
  "Irish Gambit": "Gambito Irlandês",
  "Italian Game": "Abertura Italiana",
  "Kangaroo Defense": "Defesa Canguru",
  "King's Gambit": "Gambito do Rei",
  "King's Gambit Accepted": "Gambito do Rei Aceito",
  "King's Gambit Declined": "Gambito do Rei Recusado",
  "King's Indian Attack": "Ataque Índio do Rei",
  "King's Indian Attack, with Bf5": "Ataque Índio do Rei, com Bf5",
  "King's Indian Attack, with e6": "Ataque Índio do Rei, com e6",
  "King's Indian Defense": "Defesa Índia do Rei",
  "King's Knight Opening": "Abertura do Cavalo do Rei",
  "King's Pawn Game": "Jogo do Peão do Rei",
  "King's Pawn Opening": "Abertura do Peão do Rei",
  "Kádas Opening": "Abertura Kádas",
  "Lasker Simul Special": "Especial de Simultânea de Lasker",
  "Latvian Gambit": "Gambito Letão",
  "Latvian Gambit Accepted": "Gambito Letão Aceito",
  "Lemming Defense": "Defesa Lemming",
  "Lion Defense": "Defesa Leão",
  "London System": "Sistema Londres",
  "London System, with Bd3": "Sistema Londres, com Bd3",
  "London System, with Be2": "Sistema Londres, com Be2",
  "Marienbad System": "Sistema Marienbad",
  "Mexican Defense": "Defesa Mexicana",
  "Mieses Opening": "Abertura Mieses",
  "Mikenas Defense": "Defesa Mikenas",
  "Modern Defense": "Defesa Moderna",
  "Montevideo Defense": "Defesa Montevidéu",
  "Neo-Grünfeld Defense": "Defesa Neo-Grünfeld",
  "Nimzo-Indian Defense": "Defesa Nimzo-Índia",
  "Nimzo-Larsen Attack": "Ataque Nimzo-Larsen",
  "Nimzowitsch Defense": "Defesa Nimzowitsch",
  "Old Indian Defense": "Defesa Índia Antiga",
  "Owen Defense": "Defesa Owen",
  "Paleface Attack": "Ataque Paleface",
  "Petrov's Defense": "Defesa Petrov",
  "Philidor Defense": "Defesa Philidor",
  "Pirc Defense": "Defesa Pirc",
  "Polish Defense": "Defesa Polonesa",
  "Polish Opening": "Abertura Polonesa",
  "Polish Opening, with d5": "Abertura Polonesa, com d5",
  "Ponziani Opening": "Abertura Ponziani",
  "Portuguese Opening": "Abertura Portuguesa",
  "Pseudo Queen's Indian Defense": "Pseudo Defesa Índia da Dama",
  "Pterodactyl Defense": "Defesa Pterodáctilo",
  "Queen's Gambit": "Gambito da Dama",
  "Queen's Gambit Accepted": "Gambito da Dama Aceito",
  "Queen's Gambit Declined": "Gambito da Dama Recusado",
  "Queen's Indian Accelerated": "Índia da Dama Acelerada",
  "Queen's Indian Defense": "Defesa Índia da Dama",
  "Queen's Indian Defense, with e3": "Defesa Índia da Dama, com e3",
  "Queen's Indian Defense, with e3, Bb4+ Line": "Defesa Índia da Dama, com e3, linha Bb4+",
  "Queen's Pawn Game": "Jogo do Peão da Dama",
  "Queen's Pawn, Mengarini Attack": "Peão da Dama, Ataque Mengarini",
  "Rapport-Jobava System": "Sistema Rapport-Jobava",
  "Rapport-Jobava System, with e6": "Sistema Rapport-Jobava, com e6",
  "Rat Defense": "Defesa Rato",
  "Richter-Veresov Attack": "Ataque Richter-Veresov",
  "Robatsch Defense": "Defesa Robatsch",
  "Rubinstein Opening": "Abertura Rubinstein",
  "Ruy Lopez": "Abertura Espanhola",
  "Réti Opening": "Abertura Réti",
  "Saragossa Opening": "Abertura Saragoça",
  "Scandinavian Defense": "Defesa Escandinava",
  "Scotch Game": "Abertura Escocesa",
  "Semi-Slav Defense": "Defesa Semi-Eslava",
  "Semi-Slav Defense Accepted": "Defesa Semi-Eslava Aceita",
  "Sicilian Defense": "Defesa Siciliana",
  "Slav Defense": "Defesa Eslava",
  "Slav Indian": "Índia Eslava",
  "Sodium Attack": "Ataque Sódio",
  "St. George Defense": "Defesa São Jorge",
  "Tarrasch Defense": "Defesa Tarrasch",
  "Three Knights Opening": "Abertura dos Três Cavalos",
  "Torre Attack": "Ataque Torre",
  "Trompowsky Attack": "Ataque Trompowsky",
  "Valencia Opening": "Abertura Valência",
  "Van Geet Opening": "Abertura Van Geet",
  "Van't Kruijs Opening": "Abertura Van't Kruijs",
  "Vienna Gambit, with Max Lange Defense": "Gambito Vienense, com Defesa Max Lange",
  "Vienna Game": "Abertura Vienense",
  "Vulture Defense": "Defesa Abutre",
  "Wade Defense": "Defesa Wade",
  "Ware Defense": "Defesa Ware",
  "Ware Opening": "Abertura Ware",
  "Yusupov-Rubinstein System": "Sistema Yusupov-Rubinstein",
  "Zaire Defense": "Defesa Zaire",
  "Zukertort Defense": "Defesa Zukertort",
  "Zukertort Opening": "Abertura Zukertort",
};
